// AI Tutor Scenarios for Roleplay

export const scenariosData = [
    // === ENGLISH SCENARIOS ===
    // General
    {
        language: 'en',
        slug: 'job_interview',
        title: 'Job Interview',
        titleId: 'Wawancara Kerja',
        description: 'Latihan wawancara kerja dalam Bahasa Inggris',
        category: 'general',
        context: 'You are an interviewer at a manufacturing company conducting a job interview for a factory worker position.',
        order: 1,
    },
    {
        language: 'en',
        slug: 'workplace',
        title: 'At the Workplace',
        titleId: 'Di Tempat Kerja',
        description: 'Percakapan sehari-hari di tempat kerja',
        category: 'general',
        context: 'You are a coworker or supervisor at a factory having daily conversations about work tasks.',
        order: 2,
    },
    {
        language: 'en',
        slug: 'shopping',
        title: 'Shopping',
        titleId: 'Berbelanja',
        description: 'Berbelanja dan bertransaksi',
        category: 'daily',
        context: 'You are a store clerk helping a customer with their shopping needs.',
        order: 3,
    },
    {
        language: 'en',
        slug: 'restaurant',
        title: 'At a Restaurant',
        titleId: 'Di Restoran',
        description: 'Memesan makanan di restoran',
        category: 'daily',
        context: 'You are a waiter/waitress at a restaurant taking orders and serving customers.',
        order: 4,
    },
    {
        language: 'en',
        slug: 'emergency',
        title: 'Emergency Situations',
        titleId: 'Situasi Darurat',
        description: 'Situasi darurat dan meminta bantuan',
        category: 'safety',
        context: 'Simulate emergency situations where the user needs to call for help or explain an emergency.',
        order: 5,
    },
    // Work-specific
    {
        language: 'en',
        slug: 'factory_instructions',
        title: 'Factory Instructions',
        titleId: 'Instruksi Pabrik',
        description: 'Menerima instruksi di pabrik',
        category: 'factory',
        context: 'You are a supervisor giving instructions about machine operation and safety procedures.',
        order: 6,
    },
    {
        language: 'en',
        slug: 'reporting_problems',
        title: 'Reporting Problems',
        titleId: 'Melaporkan Masalah',
        description: 'Melaporkan masalah kepada supervisor',
        category: 'work',
        context: 'You are a supervisor receiving reports about problems, defects, or issues at the workplace.',
        order: 7,
    },
    {
        language: 'en',
        slug: 'asking_leave',
        title: 'Asking for Leave',
        titleId: 'Meminta Izin',
        description: 'Meminta izin tidak masuk kerja',
        category: 'work',
        context: 'You are a supervisor or HR staff handling leave requests from employees.',
        order: 8,
    },
    {
        language: 'en',
        slug: 'safety_briefing',
        title: 'Safety Briefing',
        titleId: 'Briefing K3',
        description: 'Diskusi tentang keselamatan kerja (K3)',
        category: 'safety',
        context: 'You are a safety officer conducting a safety briefing and checking understanding.',
        order: 9,
    },
    {
        language: 'en',
        slug: 'coworker_chat',
        title: 'Chatting with Coworkers',
        titleId: 'Ngobrol dengan Rekan',
        description: 'Ngobrol santai dengan rekan kerja',
        category: 'social',
        context: 'You are a friendly coworker having casual conversations during break time.',
        order: 10,
    },
    // Daily Life
    {
        language: 'en',
        slug: 'doctor_visit',
        title: 'Visiting a Doctor',
        titleId: 'Ke Dokter',
        description: 'Pergi ke dokter dan menjelaskan gejala',
        category: 'health',
        context: 'You are a doctor at a clinic asking about symptoms and giving medical advice.',
        order: 11,
    },
    {
        language: 'en',
        slug: 'bank_account',
        title: 'Opening a Bank Account',
        titleId: 'Buka Rekening Bank',
        description: 'Membuka rekening bank',
        category: 'admin',
        context: 'You are a bank teller helping a customer open a new bank account.',
        order: 12,
    },
    {
        language: 'en',
        slug: 'renting_apartment',
        title: 'Renting an Apartment',
        titleId: 'Menyewa Apartemen',
        description: 'Mencari dan menyewa tempat tinggal',
        category: 'housing',
        context: 'You are a landlord or real estate agent showing an apartment to a potential tenant.',
        order: 13,
    },
    {
        language: 'en',
        slug: 'public_transport',
        title: 'Using Public Transport',
        titleId: 'Transportasi Umum',
        description: 'Menggunakan bus, kereta, atau taksi',
        category: 'transport',
        context: 'You are a station staff or taxi driver helping with transportation needs.',
        order: 14,
    },
    {
        language: 'en',
        slug: 'phone_call',
        title: 'Making Phone Calls',
        titleId: 'Menelepon',
        description: 'Menelepon kantor atau layanan',
        category: 'communication',
        context: 'You are a receptionist or customer service representative answering calls.',
        order: 15,
    },

    // === KOREAN SCENARIOS ===
    {
        language: 'ko',
        slug: 'job_interview',
        title: '취업 면접',
        titleId: 'Wawancara Kerja',
        description: 'Latihan wawancara kerja dalam Bahasa Korea',
        category: 'general',
        context: '당신은 공장에서 면접관 역할을 합니다. 지원자에게 경험과 능력에 대해 질문하세요.',
        order: 1,
    },
    {
        language: 'ko',
        slug: 'workplace',
        title: '직장에서',
        titleId: 'Di Tempat Kerja',
        description: 'Percakapan sehari-hari di tempat kerja',
        category: 'general',
        context: '당신은 공장에서 동료 또는 상사 역할을 합니다. 일상적인 업무 대화를 나눕니다.',
        order: 2,
    },
    {
        language: 'ko',
        slug: 'shopping',
        title: '쇼핑',
        titleId: 'Berbelanja',
        description: 'Berbelanja dan bertransaksi',
        category: 'daily',
        context: '당신은 편의점이나 마트 직원입니다. 손님을 도와주세요.',
        order: 3,
    },
    {
        language: 'ko',
        slug: 'restaurant',
        title: '식당에서',
        titleId: 'Di Restoran',
        description: 'Memesan makanan di restoran',
        category: 'daily',
        context: '당신은 식당 종업원입니다. 주문을 받고 서비스를 제공하세요.',
        order: 4,
    },
    {
        language: 'ko',
        slug: 'dormitory',
        title: '기숙사',
        titleId: 'Kehidupan Asrama',
        description: 'Kehidupan di asrama pekerja',
        category: 'housing',
        context: '당신은 기숙사 관리인입니다. 규칙과 시설에 대해 설명하세요.',
        order: 5,
    },
    {
        language: 'ko',
        slug: 'factory_instructions',
        title: '공장 지시',
        titleId: 'Instruksi Pabrik',
        description: 'Menerima instruksi di pabrik',
        category: 'factory',
        context: '당신은 공장 관리자입니다. 기계 작동과 안전 절차에 대해 지시하세요.',
        order: 6,
    },
    {
        language: 'ko',
        slug: 'reporting_problems',
        title: '문제 보고',
        titleId: 'Melaporkan Masalah',
        description: 'Melaporkan masalah kepada supervisor',
        category: 'work',
        context: '당신은 상사입니다. 직원으로부터 문제 보고를 받으세요.',
        order: 7,
    },
    {
        language: 'ko',
        slug: 'asking_leave',
        title: '휴가 신청',
        titleId: 'Meminta Izin',
        description: 'Meminta izin tidak masuk kerja',
        category: 'work',
        context: '당신은 인사 담당자입니다. 휴가 신청을 처리하세요.',
        order: 8,
    },
    {
        language: 'ko',
        slug: 'safety_training',
        title: '안전 교육',
        titleId: 'Pelatihan K3',
        description: 'Pelatihan keselamatan kerja',
        category: 'safety',
        context: '당신은 안전 담당자입니다. 안전 교육을 진행하세요.',
        order: 9,
    },
    {
        language: 'ko',
        slug: 'overtime',
        title: '야근',
        titleId: 'Lembur',
        description: 'Diskusi tentang lembur',
        category: 'work',
        context: '당신은 상사입니다. 야근에 대해 논의하세요.',
        order: 10,
    },
    {
        language: 'ko',
        slug: 'hospital',
        title: '병원',
        titleId: 'Rumah Sakit',
        description: 'Pergi ke rumah sakit',
        category: 'health',
        context: '당신은 의사입니다. 환자의 증상을 묻고 진단하세요.',
        order: 11,
    },
    {
        language: 'ko',
        slug: 'immigration',
        title: '출입국관리사무소',
        titleId: 'Kantor Imigrasi',
        description: 'Mengurus visa di imigrasi',
        category: 'admin',
        context: '당신은 출입국관리사무소 직원입니다. 비자 관련 업무를 처리하세요.',
        order: 12,
    },
    {
        language: 'ko',
        slug: 'convenience_store',
        title: '편의점',
        titleId: 'Minimarket',
        description: 'Berbelanja di minimarket',
        category: 'daily',
        context: '당신은 편의점 직원입니다. 손님을 도와주세요.',
        order: 13,
    },
    {
        language: 'ko',
        slug: 'subway',
        title: '지하철',
        titleId: 'Subway',
        description: 'Menggunakan subway',
        category: 'transport',
        context: '당신은 지하철역 직원입니다. 승객을 도와주세요.',
        order: 14,
    },

    // === JAPANESE SCENARIOS ===
    {
        language: 'ja',
        slug: 'job_interview',
        title: '就職面接',
        titleId: 'Wawancara Kerja',
        description: 'Latihan wawancara kerja dalam Bahasa Jepang',
        category: 'general',
        context: 'あなたは工場の面接官です。応募者に経験やスキルについて質問してください。',
        order: 1,
    },
    {
        language: 'ja',
        slug: 'workplace',
        title: '職場で',
        titleId: 'Di Tempat Kerja',
        description: 'Percakapan sehari-hari di tempat kerja',
        category: 'general',
        context: 'あなたは工場の同僚または上司です。日常的な仕事の会話をしてください。',
        order: 2,
    },
    {
        language: 'ja',
        slug: 'shopping',
        title: '買い物',
        titleId: 'Berbelanja',
        description: 'Berbelanja dan bertransaksi',
        category: 'daily',
        context: 'あなたはお店の店員です。お客様のお買い物をお手伝いしてください。',
        order: 3,
    },
    {
        language: 'ja',
        slug: 'restaurant',
        title: 'レストランで',
        titleId: 'Di Restoran',
        description: 'Memesan makanan di restoran',
        category: 'daily',
        context: 'あなたはレストランのウェイターです。注文を受けてサービスを提供してください。',
        order: 4,
    },
    {
        language: 'ja',
        slug: 'transportation',
        title: '交通機関',
        titleId: 'Transportasi',
        description: 'Menggunakan transportasi umum',
        category: 'transport',
        context: 'あなたは駅員またはタクシー運転手です。乗客を案内してください。',
        order: 5,
    },
    {
        language: 'ja',
        slug: 'factory_morning',
        title: '朝礼',
        titleId: 'Rapat Pagi',
        description: 'Rapat pagi di pabrik (chorei)',
        category: 'factory',
        context: 'あなたは工場の班長です。朝礼を行い、今日の作業について説明してください。',
        order: 6,
    },
    {
        language: 'ja',
        slug: 'machine_operation',
        title: '機械操作',
        titleId: 'Operasi Mesin',
        description: 'Mengoperasikan mesin',
        category: 'factory',
        context: 'あなたは機械の操作を指導する先輩です。機械の使い方を教えてください。',
        order: 7,
    },
    {
        language: 'ja',
        slug: 'quality_check',
        title: '品質検査',
        titleId: 'Quality Check',
        description: 'Pemeriksaan kualitas produk',
        category: 'factory',
        context: 'あなたは品質管理担当者です。製品の検査について説明してください。',
        order: 8,
    },
    {
        language: 'ja',
        slug: 'reporting_supervisor',
        title: '上司への報告',
        titleId: 'Melapor ke Atasan',
        description: 'Melaporkan ke supervisor',
        category: 'work',
        context: 'あなたは上司です。部下からの報告を受けてください。',
        order: 9,
    },
    {
        language: 'ja',
        slug: 'asking_overtime',
        title: '残業について',
        titleId: 'Tentang Lembur',
        description: 'Diskusi tentang lembur',
        category: 'work',
        context: 'あなたは上司です。残業について部下と話し合ってください。',
        order: 10,
    },
    {
        language: 'ja',
        slug: 'clinic',
        title: '病院・クリニック',
        titleId: 'Klinik/RS',
        description: 'Pergi ke klinik/rumah sakit',
        category: 'health',
        context: 'あなたは医者です。患者の症状を聞いて診断してください。',
        order: 11,
    },
    {
        language: 'ja',
        slug: 'city_hall',
        title: '市役所',
        titleId: 'Kantor Kota',
        description: 'Mengurus dokumen di kantor kota',
        category: 'admin',
        context: 'あなたは市役所の職員です。住民登録や書類手続きを手伝ってください。',
        order: 12,
    },
    {
        language: 'ja',
        slug: 'supermarket',
        title: 'スーパー',
        titleId: 'Supermarket',
        description: 'Berbelanja di supermarket',
        category: 'daily',
        context: 'あなたはスーパーの店員です。お客様の買い物を手伝ってください。',
        order: 13,
    },
    {
        language: 'ja',
        slug: 'apartment_rules',
        title: 'アパートのルール',
        titleId: 'Aturan Apartemen',
        description: 'Aturan tinggal di apartemen',
        category: 'housing',
        context: 'あなたはアパートの管理人です。入居者にルールを説明してください。',
        order: 14,
    },
    {
        language: 'ja',
        slug: 'emergency_call',
        title: '緊急電話 (110/119)',
        titleId: 'Telepon Darurat',
        description: 'Menelepon darurat (polisi/ambulans)',
        category: 'safety',
        context: '緊急通報の練習です。110（警察）や119（救急）への電話の仕方を練習します。',
        order: 15,
    },
];
