// AI Tutor Topics for Guided Lessons

export const topicsData = [
    // === ENGLISH TOPICS ===
    {
        language: 'en',
        slug: 'greetings',
        title: 'Greetings & Introductions',
        titleId: 'Salam & Perkenalan',
        description: 'Belajar salam dan perkenalan diri dalam Bahasa Inggris',
        category: 'basics',
        order: 1,
    },
    {
        language: 'en',
        slug: 'workplace',
        title: 'Workplace English',
        titleId: 'Bahasa Inggris Kerja',
        description: 'Bahasa Inggris untuk tempat kerja',
        category: 'work',
        order: 2,
    },
    {
        language: 'en',
        slug: 'emergency',
        title: 'Emergency Phrases',
        titleId: 'Frasa Darurat',
        description: 'Frasa untuk situasi darurat',
        category: 'safety',
        order: 3,
    },
    {
        language: 'en',
        slug: 'daily',
        title: 'Daily Conversations',
        titleId: 'Percakapan Sehari-hari',
        description: 'Percakapan untuk kehidupan sehari-hari',
        category: 'daily',
        order: 4,
    },
    {
        language: 'en',
        slug: 'numbers',
        title: 'Numbers & Time',
        titleId: 'Angka & Waktu',
        description: 'Belajar angka, waktu, dan tanggal',
        category: 'basics',
        order: 5,
    },
    {
        language: 'en',
        slug: 'directions',
        title: 'Asking Directions',
        titleId: 'Menanyakan Arah',
        description: 'Cara bertanya dan memberi petunjuk arah',
        category: 'daily',
        order: 6,
    },
    {
        language: 'en',
        slug: 'health',
        title: 'Health & Body',
        titleId: 'Kesehatan & Tubuh',
        description: 'Kosakata kesehatan dan bagian tubuh',
        category: 'health',
        order: 7,
    },
    {
        language: 'en',
        slug: 'transport',
        title: 'Transportation',
        titleId: 'Transportasi',
        description: 'Menggunakan transportasi umum',
        category: 'daily',
        order: 8,
    },

    // === KOREAN TOPICS ===
    {
        language: 'ko',
        slug: 'hangul',
        title: '한글 (Hangul)',
        titleId: 'Alfabet Korea',
        description: 'Belajar alfabet Korea dari dasar',
        category: 'basics',
        order: 1,
    },
    {
        language: 'ko',
        slug: 'greetings',
        title: '인사 (Greetings)',
        titleId: 'Salam & Perkenalan',
        description: 'Salam dan ungkapan sopan dalam Bahasa Korea',
        category: 'basics',
        order: 2,
    },
    {
        language: 'ko',
        slug: 'workplace',
        title: '직장 (Workplace)',
        titleId: 'Bahasa Korea Kerja',
        description: 'Bahasa Korea untuk lingkungan kerja',
        category: 'work',
        order: 3,
    },
    {
        language: 'ko',
        slug: 'numbers',
        title: '숫자 (Numbers)',
        titleId: 'Angka Korea',
        description: 'Belajar sistem angka Korea (native & sino)',
        category: 'basics',
        order: 4,
    },
    {
        language: 'ko',
        slug: 'daily',
        title: '일상 (Daily Life)',
        titleId: 'Kehidupan Sehari-hari',
        description: 'Percakapan sehari-hari di Korea',
        category: 'daily',
        order: 5,
    },
    {
        language: 'ko',
        slug: 'safety',
        title: '안전 (Safety)',
        titleId: 'Keselamatan Kerja',
        description: 'Istilah keselamatan kerja (K3) dalam Bahasa Korea',
        category: 'safety',
        order: 6,
    },
    {
        language: 'ko',
        slug: 'dormitory',
        title: '기숙사 (Dormitory)',
        titleId: 'Kehidupan Asrama',
        description: 'Kosakata dan percakapan di asrama pekerja',
        category: 'housing',
        order: 7,
    },
    {
        language: 'ko',
        slug: 'formal',
        title: '존댓말 (Formal Speech)',
        titleId: 'Bahasa Formal',
        description: 'Belajar bahasa formal untuk berbicara dengan atasan',
        category: 'work',
        order: 8,
    },

    // === JAPANESE TOPICS ===
    {
        language: 'ja',
        slug: 'hiragana',
        title: 'ひらがな (Hiragana)',
        titleId: 'Hiragana Dasar',
        description: 'Belajar huruf Hiragana dari awal',
        category: 'basics',
        order: 1,
    },
    {
        language: 'ja',
        slug: 'katakana',
        title: 'カタカナ (Katakana)',
        titleId: 'Katakana Dasar',
        description: 'Belajar huruf Katakana untuk kata serapan',
        category: 'basics',
        order: 2,
    },
    {
        language: 'ja',
        slug: 'greetings',
        title: '挨拶 (Greetings)',
        titleId: 'Salam & Perkenalan',
        description: 'Salam dan perkenalan dalam Bahasa Jepang',
        category: 'basics',
        order: 3,
    },
    {
        language: 'ja',
        slug: 'workplace',
        title: '職場 (Workplace)',
        titleId: 'Bahasa Jepang Kerja',
        description: 'Bahasa Jepang untuk lingkungan kerja',
        category: 'work',
        order: 4,
    },
    {
        language: 'ja',
        slug: 'numbers',
        title: '数字 (Numbers)',
        titleId: 'Angka Jepang',
        description: 'Belajar sistem angka dan counter Jepang',
        category: 'basics',
        order: 5,
    },
    {
        language: 'ja',
        slug: 'safety',
        title: '安全 (Safety)',
        titleId: 'Keselamatan Kerja',
        description: 'Istilah keselamatan kerja (K3) dalam Bahasa Jepang',
        category: 'safety',
        order: 6,
    },
    {
        language: 'ja',
        slug: 'keigo',
        title: '敬語 (Keigo)',
        titleId: 'Bahasa Sopan',
        description: 'Belajar bahasa sopan untuk berbicara dengan atasan',
        category: 'work',
        order: 7,
    },
    {
        language: 'ja',
        slug: 'daily',
        title: '日常会話 (Daily)',
        titleId: 'Percakapan Sehari-hari',
        description: 'Percakapan untuk kehidupan sehari-hari di Jepang',
        category: 'daily',
        order: 8,
    },
];
